apiVersion: v1
name: dendrite
version: "0.6.2"
description: Dendrite Matrix Homeserver
type: application
keywords:
  - matrix
  - chat
  - homeserver
  - dendrite
home: https://github.com/matrix-org/dendrite
sources:
  - https://github.com/matrix-org/dendrite
appVersion: "0.6.2"
dependencies:
- name: nats
  version: 0.10.0
  repository: https://nats-io.github.io/k8s/helm/charts
  condition: nats.enabled
- name: postgresql
  version: 10.15.1
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
