

# -- Whether or not to deploy a polylith
polylith: true

image:
  # -- Docker repository/image to use
  name: "matrixdotorg/dendrite-polylith:v0.6.0"
  # -- Kubernetes pullPolicy
  pullPolicy: IfNotPresent

configuration:
  # -- Dendrite config version
  version: 2

  # -- Servername for this Dendrite deployment
  servername: ""

  # -- The server name to delegate server-server communications to, with optional port
  # e.g. localhost:443
  well_known_server_name: ""

  # -- Lists of domains that the server will trust as identity servers to verify third
  # party identifiers such as phone numbers and email addresses.
  trusted_third_party_id_servers:
    - matrix.org
    - vector.im

  # -- Disable federation. Dendrite will not be able to make any outbound HTTP requests
  # to other servers and the federation API will not be exposed.
  disable_federation: false

  # signing key to use
  signing_key:
    # -- Create a new signing key, if not exists
    create: true
    # -- Use an existing secret
    existingSecret: ""
    
  key_validity_period: 168h0m0s


  database:
    # -- Default database host
    host:  ""
    # -- Default database user
    user:  ""
    # -- Default database password
    password: ""

    # -- Default database maximum open connections
    max_open_conns: 100
    # -- Default database maximum idle connections
    max_idle_conns: 2
    # -- Default database maximum lifetime
    conn_max_lifetime: -1

  # prometheus metrics
  metrics:
    # -- Whether or not Prometheus metrics are enabled.
    enabled: false
    # HTTP basic authentication to protect access to monitoring.
    basic_auth:
      # -- HTTP basic authentication username
      user: "metrics"
      # -- HTTP basic authentication password
      password: metrics

  # NATS connection settings
  jetstream:
    # -- The prefix to use for NATS topic names for this homeserver. Change this only if
    # you are running more than one Dendrite homeserver on the same NATS deployment.
    topic_prefix: "Dendrite"
    # -- Keep all storage in memory. This is mostly useful for unit tests.
    in_memory: false
    # -- Persistent directory to store JetStream streams in. (only relevant if not using external NATS)
    storage_path: "./"
    # -- List of NATS addresses to connect to. If empty, an in-process NATS server is used.
    addresses: []
      #- nats://nats-cluster.nats.svc.cluster.local:4222

  # TURN server information that this homeserver should send to clients.
  turn:
    turn_user_lifetime: ""
    turn_uris: []
    turn_shared_secret: ""
    # -- The TURN username
    turn_username: ""
    # -- The TURN password
    turn_password: ""
  
  rate_limiting:
    # -- Enable rate limiting
    enabled: true
    # -- After how many requests a rate limit should be activated
    threshold: 5
    # -- Cooloff time in milliseconds
    cooloff_ms: 500

  outbound_proxy:
  # -- Whether or not an outbound proxy is needed
    enabled: false
    # -- Outbound proxy protocol
    protocol: http
    # -- Outbound proxy host
    host: localhost
    # -- Outbound proxy port
    port: 8080

  dns_cache:
    # -- Whether or not the DNS cache is enabled.
    enabled: false
    # -- Maximum number of entries to hold in the DNS cache
    cache_size: 256
    # -- Duration for how long DNS cache items should be considered valid ([see time.ParseDuration](https://pkg.go.dev/time#ParseDuration) for more)
    cache_lifetime: "10m"

  # -- Default logging configuration
  # @default -- [default dendrite config values](https://github.com/matrix-org/dendrite/blob/master/dendrite-config.yaml)
  logging:
    - type: std
      level: info
    - type: file
      # The logging level, must be one of debug, info, warn, error, fatal, panic.
      level: info
      params:
        path: ./logs

  # -- Default tracing configuration
  # @default -- disabled
  tracing:
    enabled: false
    jaeger:
      serviceName: ""
      disabled: false
      rpc_metrics: false
      tags: []
      sampler: null
      reporter: null
      headers: null
      baggage_restrictions: null
      throttler: null

  profiling:
    # -- Enable pprof
    enabled: false
    # -- pprof port, if enabled
    port: 65432

  # -- Configuration for experimental MSC's. (Valid values are: msc2836 and msc2946)
  mscs: []
    # A list of enabled MSC's
    # Currently valid values are:
    # - msc2836    (Threading, see https://github.com/matrix-org/matrix-doc/pull/2836)
    # - msc2946    (Spaces Summary, see https://github.com/matrix-org/matrix-doc/pull/2946)

# -- Default resource requests/limits.
# This can be set individually for each component, see mediaapi
# @default -- sets some sane default values
resources:
  requests:
    cpu: "80m"
    memory: "64Mi"

  limits:
    cpu: "240m"
    memory: "256Mi"

persistence:
  storageClass: local-path
  logs:
    existingClaim: ""
    capacity: "10Gi"
  media:
    existingClaim: ""
    capacity: "10Gi"

# Components to deploy
# listen_int is the port for the internal api connection
# listen_ext is the port to use for external requests
# connect defines the dns and port (should be the same as listen_int) for other services to use for connections
components:
  appservice:
    # --  listen_int is the port for the internal api connection
    listen_int: 7777
    # -- Connect is the address for other components to connect to
    connect: appservice:7777

  clientapi:
    # --  listen_int is the port for the internal api connection
    listen_int: 7771
    # --  listen_ext is the port for external connections
    listen_ext: 8071
    # -- Connect is the address for other components to connect to
    connect: clientapi:7771

    registration:
      # -- Disable registration
      disabled: true

      # -- If set, allows registration by anyone who knows the shared secret, regardless of
      # whether registration is otherwise disabled.
      shared_secret: ""

      # -- enable reCAPTCHA registration
      enable_registration_captcha: false
      # -- reCAPTCHA public key 
      recaptcha_public_key: ""
      # -- reCAPTCHA private key
      recaptcha_private_key: ""
      # -- reCAPTCHA bypass secret
      recaptcha_bypass_secret: ""
      recaptcha_siteverify_api: ""

  eduserver:
    # --  listen_int is the port for the internal api connection
    listen_int: 7778
    # -- Connect is the address for other components to connect to
    connect: eduserver:7778

  federationapi:
    # --  listen_int is the port for the internal api connection
    listen_int: 7772
    # --  listen_ext is the port for external connections
    listen_ext: 8072
    # -- Connect is the address for other components to connect to
    connect: federationapi:7772
    send_max_retries: 16
    # -- Disable TLS validation
    disable_tls_validation: false
    prefer_direct_fetch: false

  keyserver:
    # --  listen_int is the port for the internal api connection
    listen_int: 7779
    # -- Connect is the address for other components to connect to
    connect: keyserver:7779

  mediaapi:
    # --  listen_int is the port for the internal api connection
    listen_int: 7774
    # --  listen_ext is the port for external connections
    listen_ext: 8074
    # -- Connect is the address for other components to connect to
    connect: mediaapi:7774
    # -- The max file size for uploaded media files
    max_file_size_bytes: "10485760"
    # Whether to dynamically generate thumbnails if needed.
    dynamic_thumbnails: false
    # -- The maximum number of simultaneous thumbnail generators to run.
    max_thumbnail_generators: 10
    # -- A list of thumbnail sizes to be generated for media content.
    # @default -- [default dendrite config values](https://github.com/matrix-org/dendrite/blob/master/dendrite-config.yaml)
    thumbnail_sizes:
    - width: 32
      height: 32
      method: crop
    - width: 96
      height: 96
      method: crop
    - width: 640
      height: 480
      method: scale
    #resources:
    #  requests:
    #    cpu: "160m"
    #    memory: "128Mi"
    #  limits:
    #    cpu: "480m"
    #    memory: "512Mi"

  roomserver:
    # --  listen_int is the port for the internal api connection
    listen_int: 7770
    # -- Connect is the address for other components to connect to
    connect: roomserver:7770

  syncapi:
    # --  listen_int is the port for the internal api connection
    listen_int: 7773
    # --  listen_ext is the port for external connections
    listen_ext: 8073
    # -- Connect is the address for other components to connect to
    connect: syncapi:7773
    # -- This option controls which HTTP header to inspect to find the real remote IP
    # address of the client. This is likely required if Dendrite is running behind
    # a reverse proxy server.
    real_ip_header: X-Real-IP

  userapi:
    # --  listen_int is the port for the internal api connection
    listen_int: 7781
    # -- Connect is the address for other components to connect to
    connect: userapi:7781

nats:
  # -- Deploy NATS JetStream dependency
  enabled: false

  nats:
    jetstream:
      # -- Enable NATS JetStream (required in polylith mode)
      enabled: true

postgresql:
  # -- Deploy PostgreSQL dependency
  enabled: false
  global:
    storageClass: ""
    postgresql:
      postgresqlDatabase: ""
      postgresqlUsername: ""
      existingSecret: ""
      postgresqlPassword: ""
      servicePort: ""
      replicationPassword: ""

  initdbScripts:
    # -- Create databases when first creating a PostgreSQL Server
    # @default -- creates the required databases
    create_db.sh: |
      #!/bin/sh
      for db in userapi_accounts userapi_devices mediaapi syncapi roomserver keyserver federationapi appservice mscs; do
          createdb -U dendrite -O dendrite dendrite_$db
      done

  persistence:
    enabled: false

ingress:
  # -- Create an ingress for a monolith deployment
  enabled: false
  
  annotations: {}
  hosts: []
  tls: []
