

# Use a polylith setup, which creates a deployment for every component.
# If false, a monolithic deployment will be created, with a single deployment.
polylith: true

# image to use
image:
  name: ""
  pullPolicy: Always

configuration:
  # servername for this dendrite deployment
  servername: ""

  # Lists of domains that the server will trust as identity servers to verify third
  # party identifiers such as phone numbers and email addresses.
  trusted_third_party_id_servers:
    - matrix.org
    - vector.im

  # signing key to use
  signing_key:
    # Create a new signing key, if not exists
    create: true
    # Use an existing secret
    existingSecret: ""
    
  key_validity_period: 168h0m0s

  # database connection settings
  database:
    host:  ""
    user:  ""
    password: ""

    max_open_conns: 100
    max_idle_conns: 2
    conn_max_lifetime: -1

  # prometheus metrics
  metrics:
    # Whether or not Prometheus metrics are enabled.
    enabled: false
    # HTTP basic authentication to protect access to monitoring.
    basic_auth:
      user: "metrics"
      password: metrics

  # kafka connection settings
  kafka:
    topic_prefix: "Dendrite"
    use_naffka: false
    use_nats: false # DO NOT USE
    max_message_bytes: 8388608
    # List of Kafka broker addresses to connect to.
    addresses:
      - kafka.kafka.svc.cluster.local:9092

  # TURN server information that this homeserver should send to clients.
  turn:
    turn_user_lifetime: ""
    turn_uris: []
    turn_shared_secret: ""
    turn_username: ""
    turn_password: ""
  
  # Settings for rate-limited endpoints. Rate limiting will kick in after the
  # threshold number of "slots" have been taken by requests from a specific
  # host. Each "slot" will be released after the cooloff time in milliseconds.
  rate_limiting:
    enabled: true
    threshold: 5
    cooloff_ms: 500

  # outbound proxy settings for federation sender
  outbound_proxy:
    enabled: false
    protocol: http
    host: localhost
    port: 8080

  dns_cache:
    # Whether or not the DNS cache is enabled.
    enabled: false
    # Maximum number of entries to hold in the DNS cache, and
    # for how long those items should be considered valid in seconds.
    cache_size: 256
    cache_lifetime: "10m"

  logging:
  - type: file
    level: "error"
    params:
      path: /var/log/dendrite

  tracing:
    enabled: false
    jaeger:
      serviceName: ""
      disabled: false
      rpc_metrics: false
      tags: []
      sampler: null
      reporter: null
      headers: null
      baggage_restrictions: null
      throttler: null

  profiling:
    enabled: false
    port: 65432

  # Configuration for experimental MSC's
  mscs:
    # A list of enabled MSC's
    # Currently valid values are:
    # - msc2836    (Threading, see https://github.com/matrix-org/matrix-doc/pull/2836)
    # - msc2946    (Spaces Summary, see https://github.com/matrix-org/matrix-doc/pull/2946)

# default resource requests/limits
resources:
  requests:
    cpu: "80m"
    memory: "64Mi"

  limits:
    cpu: "240m"
    memory: "256Mi"

persistence:
  storageClass: local-path
  logs:
    existingClaim: ""
    capacity: "10Gi"
  media:
    existingClaim: ""
    capacity: "10Gi"



# Components to deploy
# listen_int is the port for the internal api connection
# listen_ext is the port to use for external requests
# connect defines the dns and port (should be the same as listen_int) for other services to use for connections
components:
  appservice:
    listen_int: 7777
    connect: appservice:7777

  clientapi:
    listen_int: 7771
    listen_ext: 8071
    connect: clientapi:7771

    # configuration about 
    registration:
      # disable registration
      disabled: true

      # If set, allows registration by anyone who knows the shared secret, regardless of
      # whether registration is otherwise disabled.
      shared_secret: ""

      enable_registration_captcha: false
      # Settings for ReCAPTCHA.
      recaptcha_public_key: ""
      recaptcha_private_key: ""
      recaptcha_bypass_secret: ""
      recaptcha_siteverify_api: ""

  eduserver:
    listen_int: 7778
    connect: eduserver:7778

  federationapi:
    listen_int: 7772
    listen_ext: 8072
    connect: federationapi:7772

  federationsender:
    listen_int: 7775
    connect: federationsender:7775

  keyserver:
    listen_int: 7779
    connect: keyserver:7779

  mediaapi:
    listen_int: 7774
    listen_ext: 8074
    connect: mediaapi:7774
    max_file_size_bytes: 10485760
    # Whether to dynamically generate thumbnails if needed.
    dynamic_thumbnails: false
    # The maximum number of simultaneous thumbnail generators to run.
    max_thumbnail_generators: 10
    # A list of thumbnail sizes to be generated for media content.
    thumbnail_sizes:
    - width: 32
      height: 32
      method: crop
    - width: 96
      height: 96
      method: crop
    - width: 640
      height: 480
      method: scale

  roomserver:
    listen_int: 7770
    connect: roomserver:7770

  syncapi:
    listen_int: 7773
    listen_ext: 8073
    connect: syncapi:7773
    # This option controls which HTTP header to inspect to find the real remote IP
    # address of the client. This is likely required if Dendrite is running behind
    # a reverse proxy server.
    real_ip_header: X-Real-IP


  signingkeyserver:
    listen_int: 7780
    connect: signingkeyserver:7780

  userapi:
    listen_int: 7781
    connect: userapi:7781
